# Generated by Django 5.0.6 on 2024-07-13 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='name',
            new_name='first_name',
        ),
        migrations.AddField(
            model_name='order',
            name='last_name',
            field=models.CharField(default=None, max_length=30),
            preserve_default=False,
        ),
    ]
